name: Embedded Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install ClangFormat
        run: sudo apt-get install -y clang-format

      - name: Check clang version
        run: clang-format --version

      - name: Lint
        uses: wearerequired/lint-action@v2
        with:
          clang_format: true
          clang_format_dir: src/

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        git submodule update --init --recursive
    - name: Run tests on the embedded target
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
      run: |
        pio pkg install
        python scripts/replacementScript.py
        platformio remote test -e memboard -v
